# Generated by Django 5.1.1 on 2025-08-26 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscriptionplan_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gym'),
        ),
        migrations.AddField(
            model_name='staff',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gym'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gym'),
        ),
    ]
