# Generated by Django 5.1.1 on 2025-08-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_member_gym_staff_gym_trainer_gym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='gym',
        ),
    ]
