# Generated by Django 5.1.1 on 2025-08-26 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_member_gym_remove_staff_gym_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gym'),
        ),
        migrations.AddField(
            model_name='staff',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gym'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gym'),
        ),
    ]
