# Generated by Django 5.1.1 on 2025-08-26 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_member_gym_staff_gym_trainer_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gym', to=settings.AUTH_USER_MODEL),
        ),
    ]
