# Generated by Django 5.1.1 on 2025-08-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_gym_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gym_member_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
