# Generated by Django 5.1.1 on 2025-08-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_member_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('gym', 'gym_member_id')},
        ),
    ]
